import { generateText, tool as aiTool, type CoreMessage, type Tool } from "ai";
import type { z } from "zod";
import type { ProviderRegistry } from "@harness/providers";
import type { SpanCollector } from "@harness/observability";
import type { ToolRegistry } from "../tools/registry.js";
import type { ContextManager } from "../context/manager.js";
import type { LifecycleHooks } from "../hooks/lifecycle.js";

export interface LoopLimits {
  maxSteps: number;
  timeoutMs: number;
  tokenBudget: number;
  maxRetries: number;
}

export interface AgentLoopResult {
  text: string;
  steps: number;
  tokensUsed: number;
  stoppedReason: "completed" | "max_steps" | "timeout" | "token_budget" | "error";
  error?: string;
}

const DEFAULT_LIMITS: LoopLimits = {
  maxSteps: 24,
  timeoutMs: 600_000,
  tokenBudget: 500_000,
  maxRetries: 2,
};

async function runDemoAgentActions(opts: {
  role: string;
  system: string;
  prompt: string;
  tools: ToolRegistry;
  spans: SpanCollector;
}): Promise<void> {
  const write = opts.tools.get("write_file");
  if (!write) return;

  const invokeWithSpan = async (name: string, args: unknown): Promise<void> => {
    const span = opts.spans.start("tool", name, { role: opts.role, tool: name });
    const res = await opts.tools.invoke(name, args);
    if (!res.ok) {
      opts.spans.end(span, "error", { schemaPass: res.schemaPass }, res.error);
      throw new Error(res.error);
    }
    opts.spans.end(span, "ok", { schemaPass: true });
  };

  // Tech-doc workers are instructed to write docs/tech/<id>.md
  const techMatch = opts.system.match(/docs\/tech\/([a-z]+)\.md/);
  if (techMatch) {
    const id = techMatch[1];
    await invokeWithSpan("write_file", {
      path: `docs/tech/${id}.md`,
      content:
        `# ${id} (demo)\n\nGenerated in demo mode for role \`${opts.role}\`.\n\n` +
        `## Notes\n- Schema-valid pipeline artifacts still apply\n- Replace with live provider output when API keys are configured\n`,
    });
    return;
  }

  if (opts.role === "developer") {
    await invokeWithSpan("write_file", {
      path: "src/index.ts",
      content:
        `export type Item = { id: string; title: string; done: boolean };\n` +
        `const items: Item[] = [];\n` +
        `export function add(title: string): Item {\n` +
        `  const item = { id: String(items.length + 1), title, done: false };\n` +
        `  items.push(item);\n` +
        `  return item;\n` +
        `}\n` +
        `export function list(): Item[] { return [...items]; }\n` +
        `export function done(id: string): boolean {\n` +
        `  const item = items.find((i) => i.id === id);\n` +
        `  if (!item) return false;\n` +
        `  item.done = true;\n` +
        `  return true;\n` +
        `}\n`,
    });
    await invokeWithSpan("write_file", {
      path: "README.md",
      content:
        `# Demo app\n\nGenerated by The Last Harness in **demo mode** (no API keys).\n\n` +
        `Functions: \`add\`, \`list\`, \`done\` in \`src/index.ts\`.\n`,
    });
    return;
  }

  if (opts.role === "dev_validator") {
    await invokeWithSpan("write_file", {
      path: "docs/validation/demo.md",
      content: `# Validation (demo)\n\nAcceptance criteria considered satisfied in demo mode.\n`,
    });
  }
}

export async function runAgentLoop(opts: {
  role: string;
  system: string;
  prompt: string;
  providers: ProviderRegistry;
  tools: ToolRegistry;
  context: ContextManager;
  spans: SpanCollector;
  hooks: LifecycleHooks;
  limits?: Partial<LoopLimits>;
}): Promise<AgentLoopResult> {
  const limits = { ...DEFAULT_LIMITS, ...opts.limits };
  const handle = opts.providers.get(opts.role);
  const started = Date.now();
  let tokensUsed = 0;
  let steps = 0;
  let lastText = "";

  const compacted = opts.context.compact();
  const messages: CoreMessage[] = [
    {
      role: "user",
      content: `${opts.prompt}\n\n---\nContext memory:\n${compacted}`,
    },
  ];

  if (handle.demo) {
    const span = opts.spans.start("llm", `demo:${opts.role}`, {
      role: opts.role,
      model: handle.modelId,
      demo: true,
    });
    try {
      await runDemoAgentActions(opts);
      const text =
        `[[DONE]] Demo mode completed role=${opts.role}. ` +
        `No live LLM call was made.`;
      const usage = { promptTokens: 64, completionTokens: 96, totalTokens: 160 };
      opts.providers.ledger.record(opts.role, handle.config, usage);
      opts.spans.end(span, "ok", { usage, demo: true });
      opts.context.pushWorking(text);
      return {
        text,
        steps: 1,
        tokensUsed: usage.totalTokens,
        stoppedReason: "completed",
      };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      opts.spans.end(span, "error", { demo: true }, message);
      return {
        text: "",
        steps: 1,
        tokensUsed: 0,
        stoppedReason: "error",
        error: message,
      };
    }
  }

  const aiTools: Record<string, Tool> = {};
  for (const meta of opts.tools.list()) {
    const registered = opts.tools.get(meta.name);
    if (!registered) continue;
    aiTools[meta.name] = aiTool({
      description: meta.description,
      parameters: registered.inputSchema as z.ZodTypeAny,
      execute: async (args: unknown) => {
        await opts.hooks.emit("before_tool", { name: meta.name, args });
        const span = opts.spans.start("tool", meta.name, {
          role: opts.role,
          tool: meta.name,
        });
        const res = await opts.tools.invoke(meta.name, args);
        if (!res.ok) {
          opts.spans.end(span, "error", { schemaPass: res.schemaPass }, res.error);
          await opts.hooks.emit("after_tool", { name: meta.name, error: res.error });
          throw new Error(res.error);
        }
        const offloaded =
          typeof res.result === "string"
            ? opts.context.offloadToolOutput(meta.name, res.result)
            : res.result;
        opts.spans.end(span, "ok", { schemaPass: true });
        await opts.hooks.emit("after_tool", { name: meta.name, result: offloaded });
        return offloaded;
      },
    }) as Tool;
  }

  try {
    while (steps < limits.maxSteps) {
      if (Date.now() - started > limits.timeoutMs) {
        return {
          text: lastText,
          steps,
          tokensUsed,
          stoppedReason: "timeout",
        };
      }
      if (tokensUsed >= limits.tokenBudget) {
        return {
          text: lastText,
          steps,
          tokensUsed,
          stoppedReason: "token_budget",
        };
      }

      steps += 1;
      await opts.hooks.emit("before_llm", { role: opts.role, step: steps });
      const span = opts.spans.start("llm", `llm:${opts.role}`, {
        role: opts.role,
        step: steps,
        model: handle.modelId,
      });

      let attempt = 0;
      let result;
      while (true) {
        try {
          result = await generateText({
            model: handle.model,
            system: opts.system,
            messages,
            tools: Object.keys(aiTools).length ? aiTools : undefined,
            maxSteps: 1,
            temperature: handle.config.temperature ?? 0.2,
            maxTokens: handle.config.maxTokens ?? 4096,
          });
          break;
        } catch (err) {
          attempt += 1;
          if (attempt > limits.maxRetries) throw err;
        }
      }

      const usage = {
        promptTokens: result.usage.promptTokens ?? 0,
        completionTokens: result.usage.completionTokens ?? 0,
        totalTokens:
          (result.usage.promptTokens ?? 0) + (result.usage.completionTokens ?? 0),
      };
      tokensUsed += usage.totalTokens;
      opts.providers.ledger.record(opts.role, handle.config, usage);
      lastText = result.text || lastText;
      opts.spans.end(span, "ok", { usage, finishReason: result.finishReason });
      await opts.hooks.emit("after_llm", { role: opts.role, text: result.text });

      if (result.toolCalls.length === 0) {
        const exitCtx: Record<string, unknown> = {
          complete: /\[\[DONE\]\]/i.test(result.text),
          text: result.text,
        };
        await opts.hooks.emit("on_exit_attempt", exitCtx);
        if (exitCtx.continue === true && typeof exitCtx.reinjectPrompt === "string") {
          messages.push({ role: "assistant", content: result.text });
          messages.push({ role: "user", content: exitCtx.reinjectPrompt });
          opts.context.pushWorking("ralph-continuation");
          continue;
        }
        opts.context.pushWorking(`assistant: ${result.text.slice(0, 400)}`);
        return {
          text: result.text,
          steps,
          tokensUsed,
          stoppedReason: "completed",
        };
      }

      // tool results already applied via execute; keep transcript coherent
      messages.push({ role: "assistant", content: result.text || "(tool calls)" });
      messages.push({
        role: "user",
        content: `Tool results applied. Continue. When fully done, reply with [[DONE]] and a summary.`,
      });
    }

    return {
      text: lastText,
      steps,
      tokensUsed,
      stoppedReason: "max_steps",
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    await opts.hooks.emit("on_error", { error: message });
    return {
      text: lastText,
      steps,
      tokensUsed,
      stoppedReason: "error",
      error: message,
    };
  }
}
